version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
  - source: /hms-db-load-script.sql
    destination: /tmp/
    overwrite: true
    
permissions:
  - object: /var/www/html
    mode: 777
    owner: root
    type:
      - directory
  
hooks:
  BeforeInstall:
    - location: scripts/install_depend.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
    - location: scripts/enable_server.sh
      timeout: 30
      runas: root
    - location: scripts/load_db.sh
      timeout: 60
      runas: root      
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
